my_site/urls.py
from django.contrib import admin
from django.urls import path
from p_car import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index,name='index'),
]

p_car/models.py
from django.db import models

#модель автомобиля
class Car(models.Model):
    MECHANIC, AUTO, ROBOT = range(3)
    KPP_CHOICES = [
        [MECHANIC, "механика"],
        [AUTO, "автомат"],
        [ROBOT, "робот"],
    ]
    #производитель (BMW, Audi, Tesla и т.д.) (CharField)
    manufacturer = models.CharField(max_length=255)
    #модель авто (S, TT, X6 и т.д.) (CharField)
    model = models.CharField(max_length=255)
    #год выпуска (IntegerField)
    year = models.IntegerField()
    #коробка передач (SmallIntegerField with choices "механика", "автомат", "робот")
    kpp = models.SmallIntegerField(choices=KPP_CHOICES)
    #цвет
    color = models.CharField(max_length=255)

p_car/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from p_car.models import Car
from django.db.models import Q
from django.views.generic import TemplateView



def index(request):
    template = loader.get_template('index.html')
    params = request.GET
    #query с пустым Q-объектом
    query = Q()
    for key, value in params.items():
            if value and key in vars(Car):
                query &= Q(**{key: value})
    cars_data = {"cars": Car.objects.filter(query)}
    
    return HttpResponse(template.render(cars_data))

p_car/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <title>Фильтр машин</title>
</head>
<body>
    <div class="container">
        <h2>Фильтр данных</h2>
        <form action="{% url "index" %}">
            <div class="form-group">
              <label for="id_manufacturer">Производитель</label>
              <input type="text" id="id_manufacturer" name="manufacturer" class="form-control" placeholder="производитель">
            </div>
            <div class="form-group">
                <label for="id_model">Модель</label>
                <input type="text" id="id_model" name="model" class="form-control" placeholder="модель">
            </div>
            <div class="form-group">
                <label for="id_year">Год выпуска</label>
                <input type="number" id="id_year" name="year" class="form-control" placeholder="год выпуска">
            </div>
            <div class="form-group">
                <label for="id_color">Цвет</label>
                <input type="text" id="id_color" name="color" class="form-control" placeholder="Цвет">
            </div>
            <div class="form-group">
                <label for="id_kpp">Коробка передач</label>
                <select name="kpp" class="form-control" id="id_kpp">
                    <option value="" selected>Выберите коробку передач</option>
                    <option value="0">Механика</option>
                    <option value="1">Автомат</option>
                    <option value="2">Робот</option>
                </select>
              </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        
            <h2>Результат запроса</h2>
            <table class="table" border="1">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">Производитель</th>
                        <th scope="col">Модель</th>
                        <th scope="col">Год</th>
                        <th scope="col">Коробка передач</th>
                        <th scope="col">Цвет</th>
                    </tr>
                </thead>
                <tbody>
                {% for car in cars %}
               </tr>
                    <td >{{ car.manufacturer }}</td>
                    <td >{{ car.model }}</td>
                    <td >{{ car.year }}</td>
                    <td >{{ car.get_kpp_display }}</td>
                    <td >{{ car.color }}</td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        
    </div>
    <!-- jQuery -->
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>